text = input("Enter a given string: ")
uppercase_text = text.upper()
lowercase_text = text.lower()
print(f"Original text: {text}")
print(f"Uppercase: {uppercase_text}")
print(f"Lowercase: {lowercase_text}")
